spring:
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:postgresql://localhost:5432/db_bee_seller
        driverClassName: org.postgresql.Driver
        username: postgres
        password: Password1
    sql:
        init:
            mode:always

jwt:
    secret: vdgdrtta
app:
    fee-percentage: 0.5